def main():
    print(" -- ")
    print("   |")
    print("   |")
    print(" -- ")
    print("|   ")
    print("|   ")
    print(" -- ")

    print("    ")
    print("   |")
    print("   |")
    print("    ")
    print("   |")
    print("   |")
    print("    ")

    print(" --     ")
    print("   |   |")
    print("   |   |")
    print(" --     ")
    print("|      |")
    print("|      |")
    print(" --     ")

    print(" -- ", end= "")
    print("    ")
    print("   |", end= "")
    print("   |")
    print("   |", end= "")
    print("   |")
    print(" -- ", end= "")
    print("    ")
    print("|   ", end= "")
    print("   |")
    print("|   ", end= "")
    print("   |")
    print(" -- ", end= "")
    print("    ")
main()